import type { Destination } from '@/domain/model/Destination'

/**
 * Catalogo de destinos.
 *
 * Os custos em milhas sao de **ida e volta** e representam medias de mercado
 * de Latam Pass, Smiles e Azul em periodo sem promocao. Sao referencia para
 * dimensionar o resultado, nao cotacao: tarifa premiada varia por data,
 * disponibilidade e programa.
 *
 * Se a Travion tiver a tabela que usa hoje, ela substitui estes numeros — e o
 * que mais aumenta a credibilidade do resultado, porque o card mostra a milhagem
 * exigida ao lado do nome.
 *
 * A escada de precos importa tanto quanto os destinos em si: o recomendador
 * precisa de opcoes baratas o suficiente para caberem no cenario conservador e
 * caras o suficiente para o ultimo card ser aspiracional.
 */
export const DESTINATIONS: readonly Destination[] = [
  {
    id: 'rio-de-janeiro',
    name: 'Rio de Janeiro',
    country: 'Brasil',
    region: 'brasil',
    styles: ['city'],
    miles: { economy: 20_000, business: 40_000 },
    image: '/destinations/rio-de-janeiro.png',
    blurb: 'O clássico que cabe em qualquer saldo, e ainda rende fim de semana longo.',
  },
  {
    id: 'foz-do-iguacu',
    name: 'Foz do Iguaçu',
    country: 'Brasil',
    region: 'brasil',
    styles: ['city'],
    miles: { economy: 24_000, business: 48_000 },
    image: '/destinations/foz-iguacu.png',
    blurb: 'Uma das sete maravilhas naturais a três horas de voo de São Paulo.',
  },
  {
    id: 'gramado',
    name: 'Gramado',
    country: 'Brasil',
    region: 'brasil',
    styles: ['snow'],
    miles: { economy: 25_000, business: 50_000 },
    image: '/destinations/gramado.png',
    blurb: 'Frio de verdade sem sair do país, com inverno de junho a agosto.',
  },
  {
    id: 'maceio',
    name: 'Maceió',
    country: 'Brasil',
    region: 'brasil',
    styles: ['beach'],
    miles: { economy: 28_000, business: 56_000 },
    image: '/destinations/maceio.png',
    blurb: 'Piscinas naturais de água morna e o menor custo em milhas do Nordeste.',
  },
  {
    id: 'jericoacoara',
    name: 'Jericoacoara',
    country: 'Brasil',
    region: 'brasil',
    styles: ['beach'],
    miles: { economy: 30_000, business: 60_000 },
    image: '/destinations/jericoacoara.png',
    blurb: 'Dunas, lagoas e o pôr do sol que virou ponto de encontro obrigatório.',
  },
  {
    id: 'porto-de-galinhas',
    name: 'Porto de Galinhas',
    country: 'Brasil',
    region: 'brasil',
    styles: ['beach'],
    miles: { economy: 30_000, business: 60_000 },
    image: '/destinations/porto-galinhas.png',
    blurb: 'Jangada, piscina natural e resort com tudo incluído a uma hora do Recife.',
  },
  {
    id: 'buenos-aires',
    name: 'Buenos Aires',
    country: 'Argentina',
    region: 'america-do-sul',
    styles: ['city'],
    miles: { economy: 35_000, business: 70_000 },
    image: '/destinations/buenos-aires.png',
    blurb: 'O primeiro internacional da maioria: perto, barato em milhas e sempre aberto.',
  },
  {
    id: 'montevideu',
    name: 'Montevidéu',
    country: 'Uruguai',
    region: 'america-do-sul',
    styles: ['city'],
    miles: { economy: 35_000, business: 70_000 },
    image: '/destinations/montivideu.png',
    blurb: 'Rambla, parrilla e Punta del Este a duas horas de carro.',
  },
  {
    id: 'fernando-de-noronha',
    name: 'Fernando de Noronha',
    country: 'Brasil',
    region: 'brasil',
    styles: ['beach'],
    miles: { economy: 45_000, business: 90_000 },
    image: '/destinations/fernando-noronha.png',
    blurb: 'A ilha que quase todo mundo quer e quase ninguém paga em dinheiro.',
  },
  {
    id: 'santiago',
    name: 'Santiago',
    country: 'Chile',
    region: 'america-do-sul',
    styles: ['city', 'snow'],
    miles: { economy: 45_000, business: 95_000 },
    image: '/destinations/santiago.png',
    blurb: 'Vinícolas no vale e Valle Nevado a uma hora do centro.',
  },
  {
    id: 'cusco',
    name: 'Cusco e Machu Picchu',
    country: 'Peru',
    region: 'america-do-sul',
    styles: ['city'],
    miles: { economy: 50_000, business: 100_000 },
    image: '/destinations/cusco.png',
    blurb: 'A cidadela inca no alto dos Andes, uma viagem que não sai de moda.',
  },
  {
    id: 'bariloche',
    name: 'Bariloche',
    country: 'Argentina',
    region: 'america-do-sul',
    styles: ['snow'],
    miles: { economy: 55_000, business: 110_000 },
    image: '/destinations/bariloche.png',
    blurb: 'Cerro Catedral, chocolate e lago: o inverno mais acessível da América do Sul.',
  },
  {
    id: 'cartagena',
    name: 'Cartagena',
    country: 'Colômbia',
    region: 'america-do-sul',
    styles: ['beach'],
    miles: { economy: 60_000, business: 120_000 },
    image: '/destinations/cartagena.png',
    blurb: 'Cidade murada colonial de dia, Caribe colombiano de tarde.',
  },
  {
    id: 'cancun',
    name: 'Cancún',
    country: 'México',
    region: 'caribe',
    styles: ['beach'],
    miles: { economy: 70_000, business: 150_000 },
    image: '/destinations/cancun.png',
    blurb: 'Água azul-turquesa, all inclusive e Chichén Itzá no mesmo roteiro.',
  },
  {
    id: 'ushuaia',
    name: 'Ushuaia',
    country: 'Argentina',
    region: 'america-do-sul',
    styles: ['snow'],
    miles: { economy: 70_000, business: 140_000 },
    image: '/destinations/ushuaia.png',
    blurb: 'O fim do mundo, com glaciar, canal de Beagle e neve de verdade.',
  },
  {
    id: 'punta-cana',
    name: 'Punta Cana',
    country: 'República Dominicana',
    region: 'caribe',
    styles: ['beach'],
    miles: { economy: 75_000, business: 160_000 },
    image: '/destinations/punta-cana.png',
    blurb: 'Resort pé na areia onde o pacote em milhas costuma render mais que em real.',
  },
  {
    id: 'aruba',
    name: 'Aruba',
    country: 'Aruba',
    region: 'caribe',
    styles: ['beach'],
    miles: { economy: 80_000, business: 170_000 },
    image: '/destinations/aruba.png',
    blurb: 'Fora da rota de furacões: praia boa em qualquer mês do ano.',
  },
  {
    id: 'miami',
    name: 'Miami',
    country: 'Estados Unidos',
    region: 'america-do-norte',
    styles: ['beach', 'city'],
    miles: { economy: 80_000, business: 180_000 },
    image: '/destinations/miami.png',
    blurb: 'Praia, compras e o voo internacional com mais oferta de assento premiado.',
  },
  {
    id: 'orlando',
    name: 'Orlando',
    country: 'Estados Unidos',
    region: 'america-do-norte',
    styles: ['city'],
    miles: { economy: 85_000, business: 190_000 },
    image: '/destinations/orlando.png',
    blurb: 'A viagem em família que mais compensa pagar com pontos, por serem várias passagens.',
  },
  {
    id: 'lisboa',
    name: 'Lisboa',
    country: 'Portugal',
    region: 'europa',
    styles: ['city'],
    miles: { economy: 90_000, business: 200_000 },
    image: '/destinations/lisboa.png',
    blurb: 'A porta de entrada da Europa, sem barreira de idioma e com voo direto.',
  },
  {
    id: 'nova-york',
    name: 'Nova York',
    country: 'Estados Unidos',
    region: 'america-do-norte',
    styles: ['city'],
    miles: { economy: 90_000, business: 200_000 },
    image: '/destinations/nyc.png',
    blurb: 'A cidade que justifica sozinha um ano inteiro de acúmulo.',
  },
  {
    id: 'toronto',
    name: 'Toronto',
    country: 'Canadá',
    region: 'america-do-norte',
    styles: ['city'],
    miles: { economy: 95_000, business: 210_000 },
    image: '/destinations/toronto.png',
    blurb: 'Base para Niágara e para o Canadá que quase ninguém coloca no roteiro.',
  },
  {
    id: 'madri',
    name: 'Madri',
    country: 'Espanha',
    region: 'europa',
    styles: ['city'],
    miles: { economy: 100_000, business: 220_000 },
    image: '/destinations/madri.png',
    blurb: 'Prado, tapas e conexão de trem para toda a península.',
  },
  {
    id: 'barcelona',
    name: 'Barcelona',
    country: 'Espanha',
    region: 'europa',
    styles: ['beach', 'city'],
    miles: { economy: 100_000, business: 220_000 },
    image: '/destinations/barcelona.png',
    blurb: 'Gaudí de manhã e Mediterrâneo à tarde, na mesma caminhada.',
  },
  {
    id: 'amsterda',
    name: 'Amsterdã',
    country: 'Países Baixos',
    region: 'europa',
    styles: ['city'],
    miles: { economy: 105_000, business: 240_000 },
    image: '/destinations/amsterda.png',
    blurb: 'Canais, museus e o hub que abre a Europa toda em voo curto.',
  },
  {
    id: 'aspen',
    name: 'Aspen',
    country: 'Estados Unidos',
    region: 'america-do-norte',
    styles: ['snow'],
    miles: { economy: 105_000, business: 230_000 },
    image: '/destinations/aspen.png',
    blurb: 'Neve seca do Colorado, a temporada de esqui mais desejada das Américas.',
  },
  {
    id: 'paris',
    name: 'Paris',
    country: 'França',
    region: 'europa',
    styles: ['city'],
    miles: { economy: 110_000, business: 250_000 },
    image: '/destinations/paris.png',
    blurb: 'Em executiva, você chega descansado para o primeiro dia inteiro na cidade.',
  },
  {
    id: 'roma',
    name: 'Roma',
    country: 'Itália',
    region: 'europa',
    styles: ['city'],
    miles: { economy: 110_000, business: 250_000 },
    image: '/destinations/roma.png',
    blurb: 'Dois mil anos de história a cada esquina, e a comida à altura.',
  },
  {
    id: 'whistler',
    name: 'Whistler',
    country: 'Canadá',
    region: 'america-do-norte',
    styles: ['snow'],
    miles: { economy: 110_000, business: 240_000 },
    image: '/destinations/whistler.png',
    blurb: 'A maior estação de esqui da América do Norte, via Vancouver.',
  },
  {
    id: 'atenas',
    name: 'Atenas e ilhas gregas',
    country: 'Grécia',
    region: 'europa',
    styles: ['beach', 'city'],
    miles: { economy: 120_000, business: 270_000 },
    image: '/destinations/santorini.png',
    blurb: 'Acrópole e depois Santorini: história e praia na mesma viagem.',
  },
  {
    id: 'zermatt',
    name: 'Zermatt',
    country: 'Suíça',
    region: 'europa',
    styles: ['snow'],
    miles: { economy: 130_000, business: 290_000 },
    image: '/destinations/zermatt.png',
    blurb: 'Esqui aos pés do Matterhorn, o destino que fecha qualquer lista de desejos.',
  },
]
